name: Reminder System

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:

  reminder:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: test ntfy
        run: |
          curl -H "Title: test hello" -d "hello from github" https://ehovtfqbqxad.ap-southeast-1.clawcloudrun.com/lhr790827

      - name: check environment variable
        run: echo ${{ secrets.NTFY_TOPIC }}

      - name: Debug environment variable
        run: echo "NTFY_TOPIC=${{ secrets.NTFY_TOPIC }}"
      
      - name: run reminder
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python reminder.py

      - name: save state
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add state.json
          git commit -m "update reminder state $(date)" || exit 0
          git push
