name: AI Reminder

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:

  reminder:

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
         

      - name: run reminder
        env:
          NTFY_SERVER: ${{ secrets.NTFY_SERVER }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python reminder.py

      - name: generate stats
        run: python stats.py

      - name: save state
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "update data" || echo "no changes"
          git push
